.MODEL SMALL
.STACK 100H
.DATA
NUM1 DB ?
NUM2 DB ?
MSG1 DB "ENTER FIRST NUMBER TO ADD : $"
MSG2 DB 10,13, "ENTER SECOND NUMBER TO ADD : $"
MSG3 DB 10,13, "RESULT OF ADDITION IS : $"

.CODE
MAIN PROC
    ;DATA SEGMENT INITIALIZATION
    MOV AX,DATA
    MOV DS,AX
    
    ;PRINT MSG1
    LEA DX,MSG1
    MOV AH,9
    INT 21H
    
    ;FIRST NUMBER INPUT
    MOV AH,1
    INT 21H
    SUB AL,30H   ;CONVER ASCII TO BCD
    MOV NUM1,AL
    
    ;PRINT MSG2
    LEA DX,MSG2
    MOV AH,9
    INT 21H
     
    ;SECOND NUMBER INPUT
    MOV AH,1
    INT 21H
    SUB AL,30H   ;CONVER ASCII TO BCD
    MOV NUM2,AL
    
    ;ADDING TOW NUMBERS
    ADD AL,NUM1
    
    
    ;CLEARING AH REGISTER
    MOV AH,0
    
    ;FIRST DIGIT IN TO AH REGISTER
    ;SECOND DIGIT INTO AL REGISTER
    AAA
       
       
    ;CONVERT BCD TO ASCII TO SHOW OUTPUT
    ADD AH,30H
    ADD AL,30H
    
    ;MOVING THE SUM TO BX REGUSTER
    MOV BX,AX
    
    ;PRINT MSG3
    LEA DX,MSG3
    MOV AH,9
    INT 21H
    
    ;PRINT SUM
    MOV AH,2
    MOV DL,BH
    INT 21H
    MOV AH,2
    MOV DL,BL
    INT 21H
    
    ;DOS EXIT
    MOV AH,4CH
    INT 21H
    
    MAIN ENDP
END MAIN
